services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: penerimaan-karyawan-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "8001:80"
      - "5175:5175"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: penerimaan-karyawan-db
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: db_penerimaan_karyawan
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
